parameters:
    weather:
        url: "https://api.openweathermap.org"
        key: '%env(WEATHER_API_KEY)%'
        endpoints:
            geocoding: "/geo/1.0/direct"
            weather: "/daa/2.5/weather"

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
